Adds code to enrich data
metal-toolbox/trivy-extractor pull request #2
Opened 2023-07-21 15:28 UTC by angrieralien

2023-07-21 21:12 UTC, stephen-fox requested changes
In the future, can you please provide more code comments and/or commit descriptions? A pull request description would be helpful.

2023-07-21 21:12 UTC, stephen-fox commented on Dockerfile
> +FROM ubuntu:22.04
Can we use a `scratch` or distroless image instead?

2023-07-21 21:12 UTC, stephen-fox commented on internal/parse.go
> +}
I do not follow the error handling here... I think you want to know when `yaml.Unmarshal` fails, right?

2023-07-21 21:12 UTC, stephen-fox commented on get_reprots.sh
> +mkdir reports
Can you add a comment to this script that explains what it does?

2023-07-21 21:12 UTC, stephen-fox commented on internal/metrics.go
> +}
I think all of these `FakeMetricsServicer` things can be moved into the test file.

2023-07-21 21:12 UTC, stephen-fox commented on internal/metrics.go
> +					fmt.Printf("error calling metrics. %s\n", err)
Switch out `fmt` for `log` and then add `continue` after.

2023-07-21 21:12 UTC, stephen-fox commented on internal/metrics.go
> +	re := regexp.MustCompile(`} (?P<value>\d+)`)
See comment above regarding regex initialization.

2023-07-21 21:12 UTC, stephen-fox commented on internal/metrics.go
> +		return VulnMetrics{}
You can also just return `nil`. That seems to be the most common way to convey a deliberately-empty slice in my experience.

2023-07-21 21:12 UTC, stephen-fox commented on internal/metrics.go
> +		re := regexp.MustCompile(l + `="(?P<value>.*?)"`)
May as well make this a global variable.

You could also create a function that lazy loads it (so to speak). Something like this:

```go
// lazyValueRegex is initialized by valueRegex - do not reference this directly.
// Use valueRegex instead.
var lazyValueRegex *regexp.Regexp

// valueRegex initializes lazyValueRegex if it is nil and returns
// a pointer to the regex object.
func valueRegex() *regexp.Regexp {
    if lazyValueRegex == nil {
        lazyValueRegex = regexp.MustCompile(`} (?P<value>\d+)`)
    }

    return lazyValueRegex
}
```

2023-07-21 21:12 UTC, stephen-fox commented on main.go
> +	cancelChan := make(chan os.Signal, 1)
I think using `signal.NotifyContext` here (with `syscall.SIGINT` and `syscall.SIGTERM`) will simplify things quite a bit and will give you a `context.Context` you can use elsewhere.

2023-07-21 21:12 UTC, stephen-fox commented on main.go
> +	ch <- struct{}{}
Is this channel write to `ch` reachable?

2023-07-21 21:12 UTC, stephen-fox commented on main.go
> +	ps := trivy.NewPrometheusMetricsService()
You can avoid the variable naming challenges here by just calling functions / anonymously declaring objects inside of your `trivy.Report` call. For example:

```go
trivy.Report(
    &trivy.MetricsServicer{},
    trivy.NewPrometheusMetricsService(),
    ch,
    time.Second*15,
    nsTeam)
```

2023-07-21 21:12 UTC, stephen-fox commented on main.go
> +		server.Shutdown(ctx)
Not that it matters much in this scenario - but for future reference, the `context.Context` passed to `server.Shutdown` is used to bound the graceful shutdown logic to the `context.Context` being marked as done.

In other words, since `ctx` is already marked as done here, `server.Shutdown` will not wait around for any HTTP sessions to close - it will just slam them shut.

2023-07-21 21:12 UTC, stephen-fox commented on internal/namespaces.go
> +	}
Same comment here regarding error handling... I think you want to know when `f` cannot be read from.

2023-07-21 21:12 UTC, stephen-fox commented on internal/namespaces.go
> +func NewNamespaceTeam(f string) map[string]string {
Personally, I would avoid using the term `New` if there is any parsing or loading of data (especially if it can fail).

2023-07-21 21:12 UTC, stephen-fox commented on internal/namespaces.go
> +	b, err := ioutil.ReadFile(f)
ps: `ioutil` has been deprecated. There is a function with the same name in the `os` library.

2023-07-21 21:12 UTC, stephen-fox commented on internal/namespaces.go
> +	for _, l := range strings.Split(string(b[:]), "\n") {
You can also do `string(b)` - I do not think I have seen anyone express this as `string(b[:])` before.

2023-07-21 21:12 UTC, stephen-fox commented on internal/namespaces.go
> +			continue
Should there be some documentation about the order of the CSV fields? Error handling?

2023-07-21 21:12 UTC, stephen-fox commented on internal/alert.go
> +		return fmt.Errorf("cannot read reports dir")
Change to:

```go
return fmt.Errorf("cannot read reports dir - %w", err)
```

2023-07-21 21:12 UTC, stephen-fox commented on internal/metrics.go
> +func (m *MetricsServicer) Metrics() ([]string, error) {
This function should take a `context.Context` as an argument. You can then pass it to `http.NewRequestWithContext`.

2023-07-21 22:43 UTC, angrieralien commented on Dockerfile
> +FROM ubuntu:22.04
done

2023-07-21 22:48 UTC, angrieralien commented on internal/parse.go
> +}
deleted parse.go since we are just focused on metrics for this sprint. Reports was just a way to access more data regarding the vulnerabilities in the image e.g. what CVE exist.

2023-07-21 22:50 UTC, angrieralien commented on get_reprots.sh
> +mkdir reports
This just grabs all reports from all the namespaces. Deleted this since we are just focused on metrics for now.

2023-07-21 22:55 UTC, angrieralien commented on internal/metrics.go
> +}
done

2023-07-21 22:58 UTC, angrieralien commented on internal/metrics.go
> +					fmt.Printf("error calling metrics. %s\n", err)
nice catch! Done.

2023-07-21 23:06 UTC, angrieralien commented on internal/metrics.go
> +		re := regexp.MustCompile(l + `="(?P<value>.*?)"`)
done

2023-07-24 13:55 UTC, angrieralien commented on main.go
> +	ch <- struct{}{}
it is reachable. Not sure it is really necessary tho cause the program will end and close the go routine.

2023-07-24 14:10 UTC, angrieralien commented on main.go
> +	ps := trivy.NewPrometheusMetricsService()
will do

2023-07-24 15:57 UTC, angrieralien commented on internal/namespaces.go
> +	b, err := ioutil.ReadFile(f)
done

2023-07-24 16:02 UTC, angrieralien commented on internal/namespaces.go
> +	for _, l := range strings.Split(string(b[:]), "\n") {
thats just my python with numpy creeping in :)

2023-07-24 16:03 UTC, angrieralien commented on internal/namespaces.go
> +			continue
done

2023-07-25 12:58 UTC, angrieralien commented on internal/metrics.go
> +func (m *MetricsServicer) Metrics() ([]string, error) {
done

2023-07-25 18:26 UTC, stephen-fox requested changes

2023-07-25 18:26 UTC, stephen-fox commented on internal/metrics.go
> +
The `res.Body` field must have the close method called. You can add:

```go
defer res.Body.Close()
```

after the if statement.

2023-07-25 18:26 UTC, stephen-fox commented on internal/metrics.go
> +		re := regexp.MustCompile(l + `="(?P<value>.*?)"`)
I think this still needs to be made a global variable? I see the one for `} (?P<value>\d+)`.

2023-07-25 18:26 UTC, stephen-fox commented on internal/metrics.go
> +			ticker.Stop()
Can you move this under the `ticker` declaration and use `defer` instead? There are a few places in this function that return and do not call `Stop`.

2023-07-25 18:26 UTC, stephen-fox commented on internal/metrics_test.go
> +package trivy_test
Source files under the same directory should share the same package name. So, since the other source file(s) use the package name `trivy` - so should this one.

I also just noticed that this code is under `internal/`. Usually, you name packages after the directory in which they exist. For example, a package under `internal/trivy` would be named `trivy`.

2023-07-25 19:13 UTC, angrieralien commented on internal/metrics.go
> +
done

2023-07-25 19:16 UTC, angrieralien commented on internal/metrics.go
> +			ticker.Stop()
done

2023-07-25 19:17 UTC, angrieralien commented on internal/metrics_test.go
> +package trivy_test
done

2023-07-25 19:19 UTC, angrieralien commented
https://github.com/metal-toolbox/trivy-extractor/pull/2#discussion_r1273769324

if we wanted to make it global we would need 10 global variables to grab each attribute. We might be able to do one and then have match indexes to grab the value for the attribute. the reason i did it this way is in anticipation that the order changes in future releases.

2023-07-25 19:26 UTC, stephen-fox approved these changes

2023-07-27 11:56 UTC, merged